[package]
name = "pdf_reader"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf-extract = "0.7"
crossterm = "0.27"
ratatui = "0.24"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
